# Definition: CollisionSettings
0x0: unk_0x60651dc # DT_SNO : 32
0x4: unk_0x1966de6 # ActorCollisionFlags : 32
0xc: unk_0xa882afd # DT_INT : 32
0x10: unk_0x54403ff # DT_INT : 32
0x14: null or eof # DT_NULL
