# Definition: Environment
0x0: unk_0x12fbb9c # PostFXParams : 32
0x20: unk_0xcefabe9 # DT_SNO : 32
0x24: unk_0x6367947 # DT_SNO : 32
0x28: snoWeather # DT_SNO : 32
0x2c: unk_0x4c76230 # DT_SNO : 32
0x30: unk_0xafd6821 # bcQuat : 32
0x40: unk_0x580b325 # DT_SNO : 32
0x44: unk_0x9f4feca # DT_SNO : 32
0x48: unk_0xdb5ae6f # DT_FLOAT : 32
0x4c: unk_0x7680ff6 # DT_SNO : 32
0x50: unk_0x31e7772 # DT_SNO : 32
0x54: unk_0x21b2258 # DT_SNO : 32
0x58: unk_0x71767bc # DT_SNO : 32
0x5c: unk_0x96bdac9 # DT_SNO : 32
0x60: unk_0xf4f9d6f # DT_INT : 32
0x64: unk_0x55eead1 # DT_FLOAT : 32
0x68: unk_0xa7ebd97 # DT_INT : 32
0x6c: null or eof # DT_NULL
