# Definition: Environment
0x0: unk_12fbb9c # PostFXParams
0x20: unk_cefabe9 # DT_SNO (32 bits used) {group 0x1 "Actor"}
0x24: unk_6367947 # DT_SNO (32 bits used) {group 0x5d "AudioContext"}
0x28: snoWeather # DT_SNO (32 bits used) {group 0x2f "Weather"}
0x2c: unk_4c76230 # DT_SNO (32 bits used) {group 0x2c "Texture"}
0x30: unk_afd6821 # bcQuat
0x40: unk_580b325 # DT_SNO (32 bits used) {group 0x39 "Material"}
0x44: unk_9f4feca # DT_SNO (32 bits used) {group 0x39 "Material"}
0x48: unk_db5ae6f # DT_FLOAT (32 bits used)
0x4c: unk_7680ff6 # DT_SNO (32 bits used) {group 0x5 "AmbientSound"}
0x50: unk_31e7772 # DT_SNO (32 bits used) {group 0x5 "AmbientSound"}
0x54: unk_21b2258 # DT_SNO (32 bits used) {group 0x5 "AmbientSound"}
0x58: unk_71767bc # DT_SNO (32 bits used) {group 0x5 "AmbientSound"}
0x5c: unk_96bdac9 # DT_SNO (32 bits used) {group 0x5 "AmbientSound"}
0x60: unk_f4f9d6f # DT_INT (1 bits used)
0x64: unk_55eead1 # DT_FLOAT (32 bits used)
0x68: unk_a7ebd97 # DT_INT (1 bits used)
0x6c: null or eof # DT_NULL
