# Definition: ParametricSettings
# Hash: 39274139
# Flags: 00000000 00000000 00000000 00000000

0x0: unk_f1ba2b6 # DT_INT (1 bits used)
0x4: unk_fc9771a # DT_ENUM (32 bits used)
0x8: unk_fb5053f # DT_FLOAT (32 bits used)
0xc: unk_5071fb5 # DT_FLOAT (32 bits used)
0x10: fHeight # DT_INT (1 bits used)
0x14: flHeightMin # DT_FLOAT (32 bits used)
0x18: unk_b9a83c2 # DT_FLOAT (32 bits used)
0x1c: flHeightMax # DT_FLOAT (32 bits used)
0x20: unk_99ead44 # DT_FLOAT (32 bits used)
0x24: fSlope # DT_INT (1 bits used)
0x28: unk_eaf33f9 # DT_FLOAT (32 bits used)
0x2c: unk_45a7b8c # DT_FLOAT (32 bits used)
0x30: unk_eaf32fb # DT_FLOAT (32 bits used)
0x34: unk_25ea50e # DT_FLOAT (32 bits used)
0x38: fDirection # DT_INT (1 bits used)
0x3c: unk_fd4e16f # DT_FLOAT (32 bits used)
0x40: flDirectionAzimuth # DT_FLOAT (32 bits used)
0x44: unk_31d6a90 # DT_FLOAT (32 bits used)
0x48: unk_57c2f26 # DT_FLOAT (32 bits used)
0x4c: fNoise # DT_INT (1 bits used)
0x50: unk_9df1e22 # DT_FLOAT (32 bits used)
0x54: unk_da7c269 # DT_FLOAT (32 bits used)
0x58: unk_a8c1794 # DT_FLOAT (32 bits used)
0x5c: unk_a8c1696 # DT_FLOAT (32 bits used)
0x60: unk_a0f56db # DT_VECTOR2D
0x68: unk_19f3d77 # DT_INT (1 bits used)
0x6c: unk_faf93c7 # DT_FLOAT (32 bits used)
0x70: unk_d3774da # DT_FLOAT (32 bits used)
0x74: unk_faf92c9 # DT_FLOAT (32 bits used)
0x78: unk_b3b9e5c # DT_FLOAT (32 bits used)
0x7c: fInvert # DT_INT (1 bits used)
0x80: null or eof # DT_NULL
